--- #YAML:1.0
name:                Module-ThirdParty
version:             0.24
abstract:            Provide information for 3rd party modules (outside CPAN)
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
