---
name: Module-ThirdParty
version: 0.03
author:
  - Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: Provide information for 3rd party modules (outside CPAN)
license: perl
recommends:
  Module::CoreList: 0
build_requires:
  Test::More: 0
provides:
  Module::ThirdParty:
    file: lib/Module/ThirdParty.pm
    version: 0.03
generated_by: Module::Build version 0.2609
