---
name: Module-ThirdParty
version: 0.01
author:
  - Sébastien Aperghis-Tramoni <sebastien@aperghis.net>
abstract: information for 3rd party modules (outside CPAN)
license: perl
requires:
  Test::More: 0
provides:
  Module::ThirdParty:
    file: lib/Module/ThirdParty.pm
    version: 0.01
generated_by: Module::Build version 0.2609
